package com.edusoftwerks.gwtboot.cli;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Properties;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class PomUtils {

    public static String extractPackageFromPom(Path pomPath) throws IOException {
        String content = Files.readString(pomPath);

        // Try to extract from <start-class> tag
        Pattern pattern = Pattern.compile("<start-class>([a-zA-Z0-9_.]+)\\.Application</start-class>");
        Matcher matcher = pattern.matcher(content);

        if (matcher.find()) {
            return matcher.group(1);
        }

        return null;
    }

    /**
     * Reads the version number from the Maven pom.properties file packaged in the JAR.
     * This file is automatically generated by Maven during the package phase.
     *
     * @return the version string, or "unknown" if it cannot be determined
     */
    public static String getVersion() {
        try (InputStream in = PomUtils.class.getResourceAsStream(
                "/META-INF/maven/com.edusoftwerks/gwt-boot-cli/pom.properties")) {
            if (in != null) {
                Properties props = new Properties();
                props.load(in);
                return props.getProperty("version", "unknown");
            }
        } catch (IOException e) {
            // Fall through to return unknown
        }
        return "unknown";
    }

    /**
     * Reads the version from a pom.xml file directly.
     * This is useful when running from source rather than from a packaged JAR.
     *
     * @param pomPath the path to the pom.xml file
     * @return the version string, or null if it cannot be determined
     * @throws IOException if an error occurs reading the file
     */
    public static String extractVersionFromPom(Path pomPath) throws IOException {
        String content = Files.readString(pomPath);

        // Try to extract from <revision> property first (used in this project)
        Pattern revisionPattern = Pattern.compile("<revision>([^<]+)</revision>");
        Matcher revisionMatcher = revisionPattern.matcher(content);
        if (revisionMatcher.find()) {
            return revisionMatcher.group(1);
        }

        // Try to extract from <version> tag
        Pattern versionPattern = Pattern.compile("<version>([^<$]+)</version>");
        Matcher versionMatcher = versionPattern.matcher(content);
        if (versionMatcher.find()) {
            String version = versionMatcher.group(1);
            // If it's a property reference like ${revision}, try to resolve it
            if (!version.startsWith("${")) {
                return version;
            }
        }

        return null;
    }
}
